### ISSUE TITLE
Add chat

### ISSUE THREAD

**Issue by ekzyis** [jesterui/jesterui#29]
I think a chat would be cool to have if you play against real people. Haven't seen an issue about this yet.

If I have some spare time, I can try to contribute to this project :)

**Comment by theborakompanioni** [comment]
> If I have some spare time, I can try to contribute to this project :)

That'd be so awesome! It would definitely need some love. :orange_heart: 
Also, chat is a good idea, and I think simple "reactions" would already be nice.

**Comment by theborakompanioni** [comment]
Resolved with #31
