### ISSUE TITLE
Profile button not clickable

### ISSUE THREAD

**Issue by drunnells** [jesterui/jesterui#33]
At some resolutions the "Fork me on GitHub" image covers the right edge of the navigation bar making it impossible to see or click on the profile button.

![jester_profile_pic](https://user-images.githubusercontent.com/8787913/217071508-86444258-9161-4ad7-a208-fc0553a1760a.png)

**Comment by theborakompanioni** [comment]
Hey @drunnells, will be fixed asap. Thank you so much for reporting :orange_heart:
